### PR TITLE
feat(orderstatus button): ui changes

### PR DESCRIPTION
**Pull request by nidhigarg-bmw**
## Description

Order status button ui improvements

## Why

UI Enhancements as per figma

## Issue

n/a

## Checklist

Please delete options that are not relevant.

- [X] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [X] I have performed a self-review of my own code
- [X] I have successfully tested my changes locally

### CODE REVIEW

**Review by lavanya-bmw — CHANGES_REQUESTED** [review]
Please update changelog

**Comment by nidhigarg-bmw** [comment]
> Please update changelog

@lavanya-bmw Already added, no need again

**Review by lavanya-bmw — APPROVED** [review]
lgtm

**Review by oyo — CHANGES_REQUESTED** [review]
Due to a previous bug in the image component we should merge PR #91 before this. Change requested to block merging.

**Review by oyo — CHANGES_REQUESTED** [review]
please change version and changelog to 2.1.25 - otherwise okay

**Review by oyo — APPROVED** [review]

**Pull request merged**
