### PR TITLE
fix: handleChange function causing issue while selecting values from selectList component

### PR DESCRIPTION
**Pull request by shubhamv-ss**
## Description
- With ref to this PR https://github.com/eclipse-tractusx/portal-shared-components/pull/257, we need to update the condition in handleChange function so that component should update the value prop/selected value

## Why
This change is necessary to address a critical issue where the `SelectList` component does not save the selected values upon form submission, or resets them to the default values. This issue affects the data integrity and user experience, as users expect their selections to be retained and accurately reflected in the submitted data.

- **Data Integrity**: Ensuring that the selected values are correctly saved prevents data loss and maintains the integrity of the information submitted by the users.
- **User Experience**: Users need to trust that their selections are preserved. Losing or resetting the selected values can lead to frustration and errors in data entry.
- **Workflow Continuity**: Inaccurate data due to unsaved selections can disrupt workflows, leading to inefficiencies and potential issues in subsequent processes.

### Dependencies
There are no additional dependencies required for this change. The fix involves modifying the existing `SelectList` component to ensure proper handling of the selected values. 

Implementing this change will enhance the reliability and functionality of the `SelectList` component, ensuring that it meets user expectations and maintains accurate data handling across the application.

## Issue
- https://github.com/eclipse-tractusx/portal-shared-components/issues/256

## Checklist
Please delete options that are not relevant.
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally

### CODE REVIEW

**Review by lavanya-bmw — APPROVED** [review]
lgtm

**Comment by shubhamv-ss** [comment]
Is it good to merge this?
@evegufy @lavanya-bmw

**Review by evegufy — CHANGES_REQUESTED** [review]
Hi @shubhamv-ss could you please resolve the conflict?

**Comment by shubhamv-ss** [comment]
> Hi @shubhamv-ss could you please resolve the conflict?

Hi @evegufy , 
The conflicts have been addressed.

**Review by oyo — APPROVED** [review]
lgtm

**Comment by shubhamv-ss** [comment]
Hey @evegufy , sorry to bother you again. My previous PR broke this component, but this new one should fix it. We're blocked on it atm, can you take a look today? Thanks

**Review by evegufy — APPROVED** [review]

**Comment by evegufy** [comment]
> Hey @evegufy , sorry to bother you again. My previous PR broke this component, but this new one should fix it. We're blocked on it atm, can you take a look today? Thanks

@shubhamv-ss done

**Pull request merged**
