### PR TITLE
feat: add demo templates

### PR DESCRIPTION
**Pull request by manojava-gk**
## Description

static templates with react-i18next and react player support

## Why

new demo functionality

## Issue

NA

## Checklist

Please delete options that are not relevant.

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [x] I have created and linked IP issues or requested their creation by a committer
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by manojava-gk** [comment]
@evegufy Kindly help in fixing dependency check issue

**Comment by evegufy** [comment]
IP issue created: https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10673

**Review by oyo — CHANGES_REQUESTED** [review]
CHANGELOG missing & conflicts to resolve

**Comment by manojava-gk** [comment]
@oyo as you have already committed here, I'm not able to work with my local branch anymore. I have to create new PR once again.

**Comment by evegufy** [comment]
@manojava-gk IP issue was approved, you can update the dependencies file.

**Pull request closed without merging**
