### PR TITLE
fix: linting error and  warning in storybook

### PR DESCRIPTION
**Pull request by shahmargi12**
## Description

- Fix all the linting issue in library

## Why

Enabled linting in the Storybook file, which was previously disabled. Fixed all linting errors that occurred as a result.

## Issue

[#144 
](https://github.com/eclipse-tractusx/portal-shared-components/issues/144)

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally

### CODE REVIEW

**Review by oyo — CHANGES_REQUESTED** [review]
Looks good in general but two minor things:

Since we are releasing a new version on every PR merge please provide a short summary of your changes at the top of CHANGELOG.md

With `.stories.tsx` not ignored any more there are two linter complaints about strings not using single quotes which causes PR check failing. Check with `yarn lint`

**Comment by shahmargi12** [comment]
> Looks good in general but two minor things:
> 
> Since we are releasing a new version on every PR merge please provide a short summary of your changes at the top of CHANGELOG.md
> 
> With `.stories.tsx` not ignored any more there are two linter complaints about strings not using single quotes which causes PR check failing. Check with `yarn lint`

Both changes are done and pushed.

**Review by oyo — DISMISSED** [review]
looks good now - thanks for your contribution

**Comment by evegufy** [comment]
Hi @shahmargi12 could you please resolve the conflicts? I'll merge the pr afterwards. Sorry for the inconvenience.

**Comment by shahmargi12** [comment]
> Hi @shahmargi12 could you please resolve the conflicts? I'll merge the pr afterwards. Sorry for the inconvenience.

Hi @evegufy , i have resolved the conflicts and also update package version to 3.0.31.

**Review by evegufy — APPROVED** [review]

**Pull request merged**
