### PR TITLE
chore(upgrade): switch build from CRA to VITE

### PR DESCRIPTION
**Pull request by oyo**
## Description

Switch build framework from CRA to VITE

## Why

react-scripts from Create React App are deprecated for some time - we switch to the Vite framework.
Tests confirmed working:
- yarn upgrade
- library build
- unit tests
- linter
- prettier
- storybook dev server
- storybook build
- publish to NPM and use from portal-frontend

## Issue

[#92](https://github.com/eclipse-tractusx/portal-shared-components/issues/92), [#100](https://github.com/eclipse-tractusx/portal-shared-components/issues/100)

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [x] I have created and linked IP issues or requested their creation by a committer
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by evegufy** [comment]
IP issues were created:
A review is required for npm/npmjs/-/eslint-compat-utils/0.5.0.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/13999 .
A review is required for npm/npmjs/-/date-fns/3.6.0.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14000 .
A review is required for npm/npmjs/-/chromatic/11.2.0.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14001 .
A review is required for npm/npmjs/-/filesize/10.1.1.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14002 .
A review is required for npm/npmjs/-/eslint-plugin-es-x/7.6.0.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14003 .
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14004 .
A review is required for npm/npmjs/-/nypm/0.3.8.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14005 .
A review is required for npm/npmjs/-/node-fetch-native/1.6.4.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14006 .
A review is required for npm/npmjs/-/flow-parser/0.231.0.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14007 .
A review is required for npm/npmjs/-/polished/4.3.1.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14008 .
A review is required for npm/npmjs/-/react-slick/0.30.2.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14009 .
A review is required for npm/npmjs/-/ufo/1.5.3.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14010 .
A review is required for npm/npmjs/-/storybook/8.0.4.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14011 .
A review is required for npm/npmjs/-/tween-functions/1.2.0.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14012 .
A review is required for npm/npmjs/-/recast/0.23.6.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14013 .
A review is required for npm/npmjs/-/vite-plugin-dts/3.7.3.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14014 .
A review is required for npm/npmjs/-/z-schema/5.0.6.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14015 .
A review is required for npm/npmjs/-/vite-plugin-lib-inject-css/2.0.0.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14016 .
A review is required for npm/npmjs/@babel/plugin-syntax-flow/7.24.1.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14017 .
A review is required for npm/npmjs/-/unplugin/1.10.0.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14018 .
A review is required for npm/npmjs/@chromatic-com/storybook/1.2.25.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14019 .
A review is required for npm/npmjs/@mdx-js/react/3.0.1.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14020 .
A review is required for npm/npmjs/@babel/plugin-transform-flow-strip-types/7.24.1.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14021 .
A review is required for npm/npmjs/@babel/preset-flow/7.24.1.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14022 .
A review is required for npm/npmjs/@date-io/date-fns/3.0.0.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14023 .
A review is required for npm/npmjs/@storybook/addon-backgrounds/8.0.4.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14024 .
A review is required for npm/npmjs/@mui/x-date-pickers/6.19.8.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14025 .
A review is required for npm/npmjs/@mui/utils/5.15.14.
A review request already exists https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/13927 .
A review is required for npm/npmjs/@storybook/addon-actions/8.0.4.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14026 .
A review is required for npm/npmjs/@mui/x-data-grid/6.19.8.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14027 .
A review is required for npm/npmjs/@storybook/addon-controls/8.0.4.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14028 .
A review is required for npm/npmjs/@storybook/addon-docs/8.0.4.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14029 .
A review is required for npm/npmjs/@storybook/addon-highlight/8.0.4.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14030 .
A review is required for npm/npmjs/@storybook/addon-essentials/8.0.4.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14031 .
A review is required for npm/npmjs/@storybook/addon-interactions/8.0.4.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14032 .
A review is required for npm/npmjs/@storybook/addon-outline/8.0.4.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14033 .
A review is required for npm/npmjs/@storybook/addon-links/8.0.4.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14034 .
A review is required for npm/npmjs/@storybook/addon-toolbars/8.0.4.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14035 .
A review is required for npm/npmjs/@storybook/addon-onboarding/8.0.4.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14036 .
A review is required for npm/npmjs/@storybook/addon-measure/8.0.4.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14037 .
A review is required for npm/npmjs/@storybook/builder-vite/8.0.4.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14038 .
A review is required for npm/npmjs/@storybook/blocks/8.0.4.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14039 .
A review is required for npm/npmjs/@storybook/addon-viewport/8.0.4.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14040 .
A review is required for npm/npmjs/@storybook/channels/8.0.4.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14041 .
A review is required for npm/npmjs/@storybook/builder-manager/8.0.4.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14042 .
A review is required for npm/npmjs/@storybook/codemod/8.0.4.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14043 .
A review is required for npm/npmjs/@storybook/core-common/8.0.4.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14044 .
A review is required for npm/npmjs/@storybook/cli/8.0.4.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14045 .
A review is required for npm/npmjs/@storybook/client-logger/8.0.4.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14046 .
A review is required for npm/npmjs/@storybook/components/8.0.4.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14047 .
A review is required for npm/npmjs/@storybook/csf-tools/8.0.4.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14048 .
A review is required for npm/npmjs/@storybook/csf-plugin/8.0.4.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14049 .
A review is required for npm/npmjs/@storybook/core-events/8.0.4.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14050 .
A review is required for npm/npmjs/@storybook/docs-mdx/3.0.0.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14051 .
A review is required for npm/npmjs/@storybook/core-server/8.0.4.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14052 .
A review is required for npm/npmjs/@storybook/docs-tools/8.0.4.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14053 .
A review is required for npm/npmjs/@storybook/instrumenter/8.0.4.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14054 .
A review is required for npm/npmjs/@storybook/manager/8.0.4.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14055 .
A review is required for npm/npmjs/@storybook/icons/1.2.9.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14056 .
A review is required for npm/npmjs/@storybook/manager-api/8.0.4.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14057 .
A review is required for npm/npmjs/@storybook/preview/8.0.4.
GitLab API rate limit reached. Will retry in 30 seconds.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14058 .
A review is required for npm/npmjs/@storybook/react-dom-shim/8.0.4.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14059 .
A review is required for npm/npmjs/@storybook/react-vite/8.0.4.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14060 .
A review is required for npm/npmjs/@storybook/preview-api/8.0.4.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14061 .
A review is required for npm/npmjs/@storybook/node-logger/8.0.4.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14062 .
A review is required for npm/npmjs/@storybook/router/8.0.4.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14063 .
A review is required for npm/npmjs/@storybook/test/8.0.4.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14064 .
A review is required for npm/npmjs/@storybook/react/8.0.4.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14065 .
A review is required for npm/npmjs/@storybook/theming/8.0.4.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14066 .
A review is required for npm/npmjs/@storybook/telemetry/8.0.4.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14067 .
A review is required for npm/npmjs/@storybook/types/8.0.4.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14068 .
A review is required for npm/npmjs/@vitest/utils/1.4.0.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14069 .
A review is required for npm/npmjs/@vitest/utils/1.3.1.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14070 .
A review is required for npm/npmjs/@types/qs/6.9.14.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14071 .

**Review by evegufy — CHANGES_REQUESTED** [review]
@oyo I got some feedback from the EF IP team and there aren't any sources (tag for v1.2.0) available for the tween-functions package: https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14012#note_2038262

Can we find an alternative for the dev dependency @chromatic-com#storybook?:
```
yarn why tween-functions
...
=> Found "tween-functions@1.2.0"
info Reasons this module exists
   - "@chromatic-com#storybook#react-confetti" depends on it
   - Hoisted from "@chromatic-com#storybook#react-confetti#tween-functions"
```

**Comment by evegufy** [comment]
> @oyo I got some feedback from the EF IP team and there aren't any sources (tag for v1.2.0) available for the tween-functions package: https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14012#note_2038262
> 
> Can we find an alternative for the dev dependency @chromatic-com#storybook?:
> 
> ```
> yarn why tween-functions
> ...
> => Found "tween-functions@1.2.0"
> info Reasons this module exists
>    - "@chromatic-com#storybook#react-confetti" depends on it
>    - Hoisted from "@chromatic-com#storybook#react-confetti#tween-functions"
> ```

@oyo Please ignore that comment, the team decided to scan the distro instead of the repo and the package is approved now.

**Comment by oyo** [comment]
> @oyo all IP issues are approved now, please update the dependencies file and resolve the conflicts.

done - all checks have passed now

**Review by evegufy — APPROVED** [review]

**Pull request merged**
