### PR TITLE
feat(storybook): upgrade story book to support mdx files

### PR DESCRIPTION
**Pull request by manojava-gk**
## Description

update storybook versions and support mdx files
add new component specific mdx files
table component content also added

## Why

move design guidelines to storybook from assets

## Issue

#115 #223 

## Checklist

Please delete options that are not relevant.

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [x] I have created and linked IP issues or requested their creation by a committer
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by evegufy** [comment]
@manojava-gk please resolve conflicts and link previous PR, as there were a lot of discussion going on

**Comment by evegufy** [comment]
IP Issues created:
[main] INFO A review is required for npm/npmjs/-/chromatic/11.7.0.
[main] INFO A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/15843 .
[main] INFO A review is required for npm/npmjs/-/vite/5.4.0.
[main] INFO A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/15844 .

**Comment by evegufy** [comment]
@manojava-gk IP issues are already approved, you can update the DEPENDENCIES file :)

**Comment by manojava-gk** [comment]
@oyo PR is ready with necessary updates

**Review by oyo — APPROVED** [review]
lgtm now

**Pull request merged**
